# Generated by Django 3.0.7 on 2020-06-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='ansPic/%Y/%m/%D/'),
        ),
    ]
