# Generated by Django 3.0.7 on 2020-07-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_auto_20200630_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='toQuestions',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='toQuestions', to='interactions.Category'),
        ),
    ]
