# Generated by Django 3.0.7 on 2020-07-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_auto_20200701_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='toQuestions', to='interactions.Category'),
        ),
    ]
