# Generated by Django 3.0.8 on 2020-07-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_auto_20200701_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='toQuestions', to='interactions.Category'),
        ),
    ]
