# Generated by Django 3.0.8 on 2020-07-09 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0007_auto_20200707_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestTags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
