# Generated by Django 3.0.8 on 2020-08-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0011_auto_20200804_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
