# Generated by Django 3.0.8 on 2020-08-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0014_auto_20200809_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimg',
            name='imgID',
            field=models.IntegerField(null=True),
        ),
    ]
