# Generated by Django 3.0.8 on 2020-08-12 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0015_postimg_imgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interactions.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='saveBy',
            field=models.ManyToManyField(null=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='topPick',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='interactions.Answer'),
        ),
    ]
