# Generated by Django 3.0.8 on 2020-08-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0016_auto_20200812_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='comments', to='interactions.Answer'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='posts',
        ),
        migrations.AddField(
            model_name='comment',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='comments', to='interactions.Post'),
        ),
    ]
