# Generated by Django 3.0.8 on 2020-08-17 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0018_auto_20200816_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='saveBy',
        ),
        migrations.AddField(
            model_name='post',
            name='savedBy',
            field=models.ManyToManyField(blank=True, related_name='savedPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
